#!/bin/bash
ICONS=(
    # Slot placeholders
    "inventoryslot_head.jpg"
    "inventoryslot_neck.jpg"
    "inventoryslot_shoulder.jpg"
    "inventoryslot_chest.jpg"
    "inventoryslot_waist.jpg"
    "inventoryslot_legs.jpg"
    "inventoryslot_feet.jpg"
    "inventoryslot_wrists.jpg"
    "inventoryslot_hands.jpg"
    "inventoryslot_finger.jpg"
    "inventoryslot_trinket.jpg"
    "inventoryslot_mainhand.jpg"
    "inventoryslot_offhand.jpg"
    "inventoryslot_ranged.jpg"
    "inv_misc_cape_18.jpg"

    # Spells
    "spell_shadow_shadowbolt.jpg"
    "spell_shadow_abominationexplosion.jpg"
    "spell_shadow_curseofsargeras.jpg"
    "spell_shadow_chilltouch.jpg"
    "spell_shadow_requiem.jpg"
    "spell_shadow_burningspirit.jpg"
    "spell_fire_immolation.jpg"
    "spell_fire_soulburn.jpg"
    "spell_shadow_scourgebuild.jpg"
    "spell_shadow_fingerofdeath.jpg"
    "spell_shadow_summonimp.jpg"
    "spell_shadow_summonsuccubus.jpg"
    "spell_shadow_psychicscream.jpg"

    # Items
    "inv_helmet_08.jpg"
    "inv_crown_02.jpg"
    "inv_helmet_32.jpg"
    "inv_helmet_28.jpg"
    "inv_jewelry_necklace_08.jpg"
    "inv_jewelry_necklace_20.jpg"
    "inv_jewelry_necklace_07.jpg"
    "inv_shoulder_23.jpg"
    "inv_shoulder_22.jpg"
    "inv_shoulder_25.jpg"
    "inv_misc_cape_06.jpg"
    "inv_chest_cloth_21.jpg"
    "inv_misc_cape_14.jpg"
    "inv_chest_cloth_16.jpg"
    "inv_chest_cloth_18.jpg"
    "inv_bracer_07.jpg"
    "inv_bracer_09.jpg"
    "inv_gauntlets_19.jpg"
    "inv_gauntlets_17.jpg"
    "inv_gauntlets_14.jpg"
    "inv_belt_12.jpg"
    "inv_belt_22.jpg"
    "inv_belt_03.jpg"
    "inv_pants_cloth_05.jpg"
    "inv_pants_cloth_14.jpg"
    "inv_pants_cloth_08.jpg"
    "inv_boots_05.jpg"
    "inv_boots_cloth_01.jpg"
    "inv_jewelry_ring_37.jpg"
    "inv_jewelry_ring_34.jpg"
    "inv_jewelry_ring_40.jpg"
    "inv_misc_gem_pearl_04.jpg"
    "inv_jewelry_talisman_07.jpg"
    "inv_misc_herb_01.jpg"
    "inv_trinket_naxxramas04.jpg"
    "inv_jewelry_talisman_14.jpg"
    "inv_sword_39.jpg"
    "inv_weapon_shortblade_21.jpg"
    "inv_weapon_shortblade_25.jpg"
    "inv_staff_30.jpg"
    "inv_staff_33.jpg"
    "inv_misc_bag_10.jpg"
    "inv_wand_07.jpg"
    "inv_mace_14.jpg"
    "inv_wand_06.jpg"
    "inv_wand_01.jpg"
    "inv_wand_11.jpg"
)

for icon in "${ICONS[@]}"; do
    if [ ! -f "assets/icons/$icon" ]; then
        curl -s "https://wow.zamimg.com/images/wow/icons/large/$icon" -o "assets/icons/$icon"
    fi
done
echo "Downloaded $(ls assets/icons | wc -l) icons."
