#pragma once
#include "imgui.h"
#include "src/ui/asset_manager.hpp"
#include "src/ui/common/panel_spellbook.hpp"
#include <string>
#include <vector>

namespace priest
{

inline const std::vector<warlock::CommonSpellBookEntry>& get_all_priest_spellbook_entries()
{
  static const std::vector<warlock::CommonSpellBookEntry> entries = {
      {"Power Word: Fortitude", "Rank 6", "Discipline", "Instant", "1,695 Mana",
       "Increases party/target Stamina by 70 for 1 hr", "None", "—",
       "Stamina +70 (Forever buff: 70 instead of 54, 1 hr duration)", "spell_holy_wordfortitude"},
      {"Power Word: Shield", "Rank 10", "Discipline", "Instant (4s CD)", "500 Mana",
       "Absorbs 928 damage (lasts 30s)", "None", "10.0%",
       "Absorb = 928.0 + Healing * 0.10 * Multipliers (Weakened Soul: 15s)", "spell_holy_powerwordshield"},
      {"Confounding Flash", "—", "Discipline", "0.5s (2m CD)", "3% base",
       "Confuses up to 5 enemies within 8 yds for 3 sec", "None", "—",
       "Crowd Control: Breaks on any damage taken", "ability_paladin_blindinglight2"},
      {"Starshards", "Rank 7", "Arcane", "Channeled (30s CD)", "350 Mana",
       "None", "1,800 Base Arcane DoT over 6s (6 ticks of 300.0 every 1s)", "100.0%",
       "Tick = (300.0 + ArcaneSP * 0.1667) * Multipliers [Forever: 100% SP, 30s CD]", "spell_arcane_starfire"},
      {"Inner Fire", "Rank 6", "Discipline", "Instant", "315 Mana",
       "Increases Armor by 1,395 (20 charges, 10 min)", "None", "—",
       "Armor +1395 (Consumes 1 charge per melee/ranged hit taken)", "spell_holy_innerfire"},
      {"Dispel Magic", "Rank 2", "Discipline", "Instant", "18% base",
       "Dispels 2 harmful (friendly) or 2 beneficial (enemy) effects", "None", "—",
       "Magic Purge / Cleanse (up to 2 effects per cast)", "spell_holy_dispelmagic"},
      {"Contingency Plan", "Rank 5", "Discipline", "Instant (10m CD)", "0 Mana",
       "Ward ally for 30s: if HP < 35%, gains shield & heal over 15s", "None", "—",
       "Emergency Cheat-Death Ward (1 target per caster, 10 min CD)", "ability_priest_soulwarding"},
      {"Elune's Grace", "—", "Discipline", "Instant (5m CD)", "3% base",
       "Reduces chance to be hit by melee/ranged by 50% (15s or 3 misses)", "None", "—",
       "Defensive: 50% evasion vs melee/ranged attacks (Forever: 3% base mana)", "spell_holy_elunesgrace"},
      {"Feedback", "Rank 5", "Discipline", "Instant (3m CD)", "230 Mana",
       "Burns 105 attacker Mana & deals 105 Shadow Dmg on hostile cast (15s)", "None", "—",
       "Anti-Magic Shield: 105 Mana Burn + 1:1 Shadow Damage on spell hit", "spell_shadow_ritualofsacrifice"},
      {"Shackle Undead", "Rank 3", "Discipline", "1.5s", "150 Mana",
       "Shackles target undead enemy for up to 50 sec", "None", "—",
       "Crowd Control: Undead incapacitated (breaks on damage)", "spell_nature_slow"},
      {"Mana Burn", "Rank 5", "Discipline", "3.0s", "270 Mana",
       "Drains 738 - 780 Mana from target", "Deals 50% of Mana drained as Shadow damage (369 - 390)", "—",
       "Mana Drained = Roll(738, 780) | Shadow Damage = Mana Drained * 0.50", "spell_shadow_manaburn"},
      {"Divine Spirit", "Rank 4", "Discipline", "Instant", "970 Mana",
       "Increases target Spirit by 40 for 1 hr", "None", "—",
       "Spirit +40 (Forever buff: 1 hr duration)", "spell_holy_divinespirit"},
      {"Penance", "Rank 4", "Discipline", "Channeled (12s CD)", "355 Mana",
       "131 Holy Damage or 673 Healing per tick (3 ticks over 2s)", "None", "75.0%",
       "Damage = 131 + SP * 0.25/sec | Heal = 673 + Healing * 0.25/sec", "spell_holy_penance"},
      {"Levitate", "—", "Discipline", "Instant", "100 Mana",
       "Slow fall and water walking for 2 min (requires Light Feather)", "None", "—",
       "Utility: Reduced falling speed and liquid walking", "spell_holy_layonhands"},
      {"Prayer of Fortitude", "Rank 2", "Discipline", "Instant", "3,400 Mana",
       "Party/Raid: Increases Stamina by 70 for 1 hr", "None", "—",
       "Party Stamina +70 (Forever buff: 70 instead of 54, 1 hr duration)", "spell_holy_prayeroffortitude"},
      {"Prayer of Spirit", "—", "Discipline", "Instant", "1,940 Mana",
       "Party/Raid: Increases Spirit by 40 for 1 hr", "None", "—",
       "Party Spirit +40 (Forever buff: 1 hr duration)", "spell_holy_prayerofspirit"},
      {"Lesser Heal", "Rank 3", "Holy", "2.5s", "75 Mana",
       "130 - 152 Direct Healing", "None", "71.43%",
       "Heal = Roll(130, 152) + Healing * 0.71429 * Multipliers", "spell_holy_lesserheal"},
      {"Smite", "Rank 8", "Holy", "2.5s", "280 Mana",
       "160 - 180 Direct Holy Damage", "None", "71.43%",
       "Damage = Roll(160, 180) + HolySP * 0.71429 * Multipliers [Forever: 71.4% SP]", "spell_holy_holysmite"},
      {"Renew", "Rank 10", "Holy", "Instant", "410 Mana",
       "None", "830 Base Healing over 15s (5 ticks of 166.0 every 3s)", "100.0%",
       "Tick = (166.0 + Healing * 0.20) * Multipliers [Forever: 20%/tick = 100% total]", "spell_holy_renew"},
      {"Desperate Prayer", "Rank 7", "Holy", "Instant (10m CD)", "0 Mana",
       "1,269 - 1,497 Direct Self-Healing", "None", "42.86%",
       "Heal = Roll(1269, 1497) + Healing * 0.42857 * Multipliers", "spell_holy_restoration"},
      {"Divine Grace", "Rank 7", "Holy", "Instant (10m CD)", "0 Mana",
       "1,269 - 1,497 Direct Healing (<50% HP ally) + removes Weakened Soul", "None", "42.86%",
       "Heal = Roll(1269, 1497) + Healing * 0.42857 | Clears Weakened Soul", "ability_priest_savinggrace"},
      {"Resurrection", "Rank 5", "Holy", "10.0s", "75% base",
       "Revives dead player with 750 HP and 1,000 Mana (Out of Combat)", "None", "—",
       "Resurrection: 750 HP + 1000 Mana restore", "spell_holy_resurrection"},
      {"Cure Disease", "—", "Holy", "Instant", "15% base",
       "Removes 1 disease effect from friendly target", "None", "—",
       "Dispel: 1 disease aura", "spell_holy_nullifydisease"},
      {"Heal", "Rank 4", "Holy", "3.0s", "305 Mana",
       "611 - 691 Direct Healing", "None", "85.71%",
       "Heal = Roll(611, 691) + Healing * 0.85714 * Multipliers", "spell_holy_heal02"},
      {"Chastise", "Rank 5", "Holy", "Instant (2m CD)", "225 Mana",
       "272 - 306 Holy Damage (Immobilizes Humanoid 2s, low threat)", "None", "42.86%",
       "Damage = Roll(272, 306) + HolySP * 0.42857 * Multipliers", "spell_holy_chastise"},
      {"Fear Ward", "—", "Holy", "Instant (3m CD)", "100 Mana",
       "Wards friendly target against next Fear effect (lasts 3 min)", "None", "—",
       "Fear Immunity Ward (Forever: 3 min CD, 3 min duration)", "spell_holy_excorcism"},
      {"Flash Heal", "Rank 7", "Holy", "1.5s", "380 Mana",
       "757 - 893 Direct Healing", "None", "85.71%",
       "Heal = Roll(757, 893) + Healing * 0.85714 * Multipliers", "spell_holy_flashheal"},
      {"Holy Fire", "Rank 8", "Holy", "3.5s", "255 Mana",
       "184 - 232 Initial Holy Damage", "75 Base DoT over 10s (5 ticks of 15.0 every 2s, 259 - 307 Total)", "100.0%",
       "Direct = Roll(184, 232) + SP * 0.75 | Dot = 75 + SP * 0.25 (100% total)", "spell_holy_searinglight"},
      {"Holy Nova", "Rank 6", "Holy", "Instant", "750 Mana",
       "174 - 200 Holy Dmg (enemies <=10y) / 288 - 334 Healing (allies <=10y)", "None", "16.1% / 30.3%",
       "Damage = Roll(174, 200) + SP * 0.161 | Heal = Roll(288, 334) + Healing * 0.303", "spell_holy_holynova"},
      {"Binding Heal", "Rank 6", "Holy", "1.5s", "380 Mana",
       "757 - 893 Direct Healing to target and caster (low threat)", "None", "85.71%",
       "Heal = Roll(757, 893) + Healing * 0.85714 (Heals ally + self)", "spell_holy_blindingheal"},
      {"Prayer of Healing", "Rank 5", "Holy", "3.0s", "1,070 Mana",
       "631 - 667 Healing to party members within 40 yds", "None", "300.0%",
       "Heal = Roll(631, 667) + Healing * 0.60 per member (300% total party coeff)", "spell_holy_prayerofhealing02"},
      {"Abolish Disease", "—", "Holy", "Instant", "15% base",
       "Cures 1 disease effect instantly and 1 every 5s for 20s", "None", "—",
       "Periodic Cleanse: Up to 5 disease dispels over 20s", "spell_nature_nullifydisease"},
      {"Greater Heal", "Rank 5", "Holy", "3.0s", "710 Mana",
       "1,853 - 2,067 Direct Healing", "None", "85.71%",
       "Heal = Roll(1853, 2067) + Healing * 0.85714 * Multipliers", "spell_holy_greaterheal"},
      {"Lightwell", "Rank 3", "Holy", "1.5s (10m CD)", "365 Mana",
       "Creates Lightwell (3 min, 5 charges): click restores 1,600 HP over 10s", "None", "—",
       "Interactive Healing Beacon (5 clicks, cancel on damage)", "spell_holy_summonlightwell"},
      {"Prayer of Mending", "Rank 3", "Holy", "Instant (10s CD)", "390 Mana",
       "Heals 413 on damage taken, jumps to ally <=20 yds up to 5 times", "None", "42.86%",
       "Heal = 413 + Healing * 0.42857 per jump (5 jumps max, lasts 30s)", "spell_holy_prayerofmendingtga"},
      {"Shadow Word: Pain", "Rank 8", "Shadow", "Instant", "470 Mana",
       "None", "762 Base Shadow DoT over 18s (6 ticks of 127.0 every 3s)", "120.0%",
       "Tick = (127.0 + ShadowSP * 0.20) * Multipliers [Forever: 120.0% SP total]", "spell_shadow_shadowwordpain"},
      {"Fade", "Rank 6", "Shadow", "Instant (30s CD)", "275 Mana",
       "Temporarily reduces priest's threat for 10 sec", "None", "—",
       "Temporary Threat Drop: Threat returns after 10s expires", "spell_magic_lesserinvisibilty"},
      {"Hex of Weakness", "Rank 6", "Shadow", "Instant", "240 Mana",
       "Target Melee Attack Power -204 and Healing Received -20% (2 min)", "None", "—",
       "Debuff: -204 AP and -20% healing received (lasts 2 min)", "spell_shadow_fingerofdeath"},
      {"Mind Blast", "Rank 9", "Shadow", "1.5s (8s CD)", "350 Mana",
       "472 - 498 Direct Shadow Damage (High Threat)", "None", "42.86%",
       "Damage = Roll(472, 498) + ShadowSP * 0.42857 * Multipliers [Forever: 42.9% SP]", "spell_shadow_unholyfrenzy"},
      {"Touch of Weakness", "Rank 6", "Shadow", "Instant", "195 Mana",
       "56 Shadow Damage on next melee hit taken & -204 attacker AP (2 min)", "None", "10.0%",
       "Retaliation Damage = 56.0 + ShadowSP * 0.10 | Debuff: -204 AP", "spell_shadow_deadofnight"},
      {"Psychic Scream", "Rank 4", "Shadow", "Instant (30s CD)", "210 Mana",
       "Causes up to 5 enemies within 8 yds to flee for 8 sec", "None", "—",
       "AoE Fear: Breaks on damage taken", "spell_shadow_psychicscream"},
      {"Dark Sacrifice", "Rank 5", "Shadow", "Instant (10m CD)", "0 Mana",
       "Cannibalizes 1,600 Health over 15s to gain 1,600 Mana", "None", "—",
       "Mana Conversion: Transfers 1600 HP into 1600 Mana over 15s", "spell_holy_powerinfusion_shadow"},
      {"Devouring Plague", "Rank 6", "Shadow", "Instant (1m CD)", "985 Mana",
       "None", "848 Base Shadow DoT over 24s (8 ticks of 106.0 every 3s, heals caster)", "80.0%",
       "Tick = (106.0 + ShadowSP * 0.10) * Multipliers [Forever: 80.0% SP, 1 min CD]", "spell_shadow_devouringplague"},
      {"Mind Flay", "Rank 6", "Shadow", "Channeled 3.0s", "205 Mana",
       "None", "390 Base Shadow Damage over 3s (3 ticks of 130.0 every 1s, 50% slow)", "50.0%",
       "Tick = (130.0 + ShadowSP * 0.1667) * Multipliers [Forever: 50.0% SP total]", "spell_shadow_siphonmana"},
      {"Mind Soothe", "Rank 3", "Shadow", "Instant", "90 Mana",
       "Reduces aggro radius of Humanoid target (<= lvl 70) by 10 yds (15s)", "None", "—",
       "Aggro Radius Reduction: -10 yds for 15s", "spell_holy_mindsooth"},
      {"Shadowguard", "Rank 6", "Shadow", "Instant", "250 Mana",
       "Attacker struck for 96 Shadow Damage on hit (3 charges, lasts 10 min)", "None", "80.0%",
       "Damage = 96.0 + ShadowSP * 0.2667 per charge (80% total coeff, low threat)", "spell_nature_lightningshield"},
      {"Mind Vision", "Rank 2", "Shadow", "Channeled 1.0m", "150 Mana",
       "Allows caster to see through target's eyes for 1 min", "None", "—",
       "Target Scouting Vision (Same continent/instance)", "spell_holy_mindvision"},
      {"Mind Control", "Rank 3", "Shadow", "Channeled 1.0m", "750 Mana",
       "Controls humanoid mind up to lvl 62 for up to 1 min (+25% attack speed)", "None", "—",
       "Channeled Mind Control: Increases time between attacks by 25%", "spell_shadow_shadowworddominate"},
      {"Shadow Protection", "Rank 3", "Shadow", "Instant", "650 Mana",
       "Increases target's Shadow Resistance by 60 for 10 min", "None", "—",
       "Shadow Resistance +60 (10 min duration)", "spell_shadow_antishadow"},
      {"Shadow Word: Death", "Rank 4", "Shadow", "Instant (15s CD)", "340 Mana",
       "434 - 462 Direct Shadow Damage (Backlash: 10% max HP if survives)", "None", "42.86%",
       "Damage = Roll(434, 462) + ShadowSP * 0.42857 * Multipliers [Forever Rank 4]", "spell_shadow_demonicfortitude"},
      {"Prayer of Shadow Protection", "—", "Shadow", "Instant", "1,300 Mana",
       "Party/Raid: Increases Shadow Resistance by 60 for 20 min", "None", "—",
       "Party Shadow Resistance +60 (20 min duration)", "spell_holy_prayerofshadowprotection"},
  };
  return entries;
}

inline void render_priest_spellbook_panel()
{
  static char search_filter[64] = "";
  const auto& entries = get_all_priest_spellbook_entries();

  warlock::render_unified_spellbook_table("PriestSpellbookTable",
                                          "Search Spells (e.g. Shadow Word, Holy)...",
                                          search_filter, sizeof(search_filter),
                                          entries);
}

}  // namespace priest
