// Level-60 Forever racial data. Class spell sources are linked on each entry.
// General racial tooltips: https://foreverdb.net/races
export const PRIEST_RACES = Object.freeze(['HUMAN','UNDEAD','NIGHT_ELF','DWARF','GNOME','TROLL']);
export const RACE_NAMES = Object.freeze({HUMAN:'Human',UNDEAD:'Undead',NIGHT_ELF:'Night Elf',DWARF:'Dwarf',GNOME:'Gnome',TROLL:'Troll'});
export const RACE_ICONS = Object.freeze({HUMAN:'Achievement_Character_Human_Male.png',UNDEAD:'Achievement_Character_Undead_Male.png',NIGHT_ELF:'Inv_Misc_Tournaments_Symbol_NightElf.png',DWARF:'Inv_Misc_Tournaments_Symbol_Dwarf.png',GNOME:'Inv_Misc_Tournaments_Symbol_Gnome.png',TROLL:'Inv_Misc_Tournaments_Symbol_Troll.png'});
const spell=(name,id,icon,description,coverage)=>Object.freeze({name,id,icon,description,coverage,source:`https://www.wowhead.com/forever/spell=${id}`});
export const PRIEST_RACIALS=Object.freeze({
 HUMAN:[spell('Divine Grace',1277378,'ability_priest_savinggrace.png','Free instant heal: 1318–1546 + 0.429 × healing power; ally below 50% Health only. Removes Weakened Soul. 40 yd; 10 min cooldown.','Heals the configured ally; unavailable in Shadowform.'),spell('Feedback',19275,'spell_shadow_ritualofsacrifice.png','230 mana; 15 sec aura; 3 min cooldown. Incoming successful spells burn up to 105 enemy mana and deal that much Shadow damage.','Requires incoming spell attacks and enemy mana.'),spell('The Human Spirit',20598,'Spell_Holy_MagicalSentry.png','Spirit increased by 5%.','Applied to Spirit, regeneration and Spiritual Guidance.')],
 UNDEAD:[spell('Dark Sacrifice',1277328,'spell_holy_powerinfusion_shadow.png','Converts 1600 Health into 1600 + 100% of Spirit mana over 15 sec, in five 3 sec ticks. Instant; 10 min cooldown.','Used when the mana deficit covers the return and Health exceeds 1600.'),spell('Touch of Weakness',19266,'spell_shadow_deadofnight.png','195 mana. The next melee hit triggers 56 + 0.107 × Shadow spell power damage and reduces melee attack power by 204 for 2 min. Buff lasts 10 min.','Requires incoming melee hits; reapplied after consumption.'),spell('Touch of the Grave',1260198,'Spell_Shadow_FingerOfDeath.png','Damaging spell casts have a 10% chance to drain 5% of maximum Health. Periodic ticks cannot trigger it.','Triggered once per damaging spell cast; no extra proc from its own damage.')],
 NIGHT_ELF:[spell('Starshards',19305,'spell_arcane_starfire.png','350 mana; instant; 30 yd; 30 sec cooldown. Six 1 sec Arcane ticks of 300 + 0.167 × spell power.','Used by damage policies.'),spell("Elune's Grace",2651,'spell_holy_elunesgrace.png','3% base mana. Melee/ranged hit chance reduced by 50 percentage points for 15 sec or until 3 misses. 5 min cooldown.', 'Requires incoming melee or ranged attacks.'),spell("Elune's Light",1259799,'Spell_Holy_ElunesGrace.png','Adds 10 percentage points to all spell critical chances for 15 sec. Off GCD; 3 min cooldown.','Used on cooldown before damage spells.')],
 DWARF:[spell('Chastise',1277335,'spell_holy_chastise.png','225 mana; instant; 20 yd; 2 min cooldown. 272–306 + 0.143 × Holy spell power damage; roots a Humanoid for 2 sec. Very low threat.','Humanoid damage only; root prevents out-of-reach melee attacks.'),spell('Desperate Prayer',19243,'spell_holy_restoration.png','Free instant self-heal: 1318–1546 + 0.429 × healing power. 10 min cooldown.','Used below 50% Health; unavailable in Shadowform.'),spell('Big Game Hunter',20596,'Ability_Hunter_SniperShot.png','Damage against Beasts increased by 5%.','Requires a Beast target.'),spell('Mace Specialization',59224,'INV_Mace_01.png','Spell and attack critical chance increased by 1% while holding a mace.','Applied only when the weapon selector is Mace.')],
 GNOME:[spell('Confounding Flash',1277455,'ability_paladin_blindinglight2.png','3% base mana; 0.5 sec cast; 8 yd; 2 min cooldown. Confuses up to 5 enemies for 3 sec; damage breaks it.','The single simulated target stops attacking until damaged; control immunity respected.'),spell('Contingency Plan',1277640,'ability_priest_soulwarding.png','Free instant 30 sec ward; 30 yd; 10 min cooldown. A hit dropping the ally below 35% Health triggers a 926 shield and 670 healing over 15 sec.','Configured ally; server-side scaling is not available in client data. Uses the verified level-60 tooltip values.'),spell('Eureka!',1259823,'Spell_Arcane_MindMastery.png','Next 3 non-periodic damaging or healing abilities cost 10% less mana and deal/heal 10% more. Off GCD; 15 sec duration; 2 min cooldown.','Channels qualify; DoT ticks do not gain damage.'),spell('Expansive Mind',20591,'INV_Enchant_EssenceEternalLarge.png','Maximum mana increased by 5%.','Applied after Intellect and Mental Strength.')],
 TROLL:[spell('Hex of Weakness',19285,'spell_shadow_fingerofdeath.png','240 mana; instant; 30 yd. Reduces melee attack power by 204 and healing received by 20% for 2 min.','Used against incoming melee or enemy healing; attack-power debuffs do not stack.'),spell('Shadowguard',19312,'spell_nature_lightningshield.png','250 mana; instant. Three charges, 10 min duration. Incoming hits trigger Shadow damage; no threat.','Uses the current 96-damage tooltip + 0.267 × spell power (the old aura still says 116); 3.5 sec proc interval.'),spell('Berserking',26297,'Racial_Troll_Berserk.png','10% faster casting/attacks for 10 sec. Off GCD; 3 min cooldown.','Speeds casts, channels, GCD (1 sec minimum) and wand interval; cooldowns and DoT tick intervals stay fixed.'),spell('Beast Slaying',20557,'Ability_Mount_Raptor.png','Damage against Beasts increased by 5%.','Requires a Beast target.')]
});
export const RACIAL_DEFAULTS=Object.freeze({race:0,racialsEnabled:0,maxHealth:5000,initialHealthRatio:1,baseMana:1456,spirit:0,healingPower:0,healingMultiplier:1,shadowformEnabled:0,manaCapacityMultiplier:1,targetIsHumanoid:0,targetIsBeast:0,targetControlImmune:1,weaponIsMace:0,incomingAttackInterval:0,incomingAttackType:1,incomingDamage:0,incomingHitChance:1,enemyAttackSpeed:2,enemyHealingPerTick:0,allyMaxHealth:5000,allyInitialHealthRatio:1,allyAttackInterval:0,allyIncomingDamage:0,allyDistance:0,allyWeakenedSoul:0,shadowguardProcInterval:3.5,graveProcInterval:0});
export const RACIAL_CONFIG=Object.freeze(Object.fromEntries(Object.keys(RACIAL_DEFAULTS).map(key=>[key,['race','racialsEnabled','shadowformEnabled','targetIsHumanoid','targetIsBeast','targetControlImmune','weaponIsMace','incomingAttackType'].includes(key)?'u32':'f32'])));
export const RACIAL_BOUNDS=Object.freeze({race:[0,5],racialsEnabled:[0,1],maxHealth:[1,1000000],initialHealthRatio:[0.001,1],baseMana:[1,1000000],spirit:[0,20000],healingPower:[0,20000],healingMultiplier:[1,2],shadowformEnabled:[0,1],manaCapacityMultiplier:[1,1.05],targetIsHumanoid:[0,1],targetIsBeast:[0,1],targetControlImmune:[0,1],weaponIsMace:[0,1],incomingAttackInterval:[0,1800],incomingAttackType:[1,3],incomingDamage:[0,1000000],incomingHitChance:[0,1],enemyAttackSpeed:[0.1,10],enemyHealingPerTick:[0,1000000],allyMaxHealth:[1,1000000],allyInitialHealthRatio:[0.001,1],allyAttackInterval:[0,1800],allyIncomingDamage:[0,1000000],allyDistance:[0,100],allyWeakenedSoul:[0,15],shadowguardProcInterval:[0.001,60],graveProcInterval:[0,60]});
export const RACIAL_STATE=Object.freeze({playerHealth:'f32',allyHealth:'f32',healingDone:'f32',absorbed:'f32',damageTaken:'f32',damagePrevented:'f32',enemyHealingPrevented:'f32',darkSacrificeMana:'f32',healthSpent:'f32',elunesLightUses:'u32',eurekaUses:'u32',berserkingUses:'u32',deathTimeMs:'u32',allyWeakenedSoulRemainingMs:'u32',healing18:'f32',healing19:'f32',healing20:'f32'});
export const RACIAL_IDS=Object.freeze({chastise:12,shadowguard:13,feedback:14,touchWeakness:15,hexWeakness:16,darkSacrifice:17,desperatePrayer:18,divineGrace:19,contingencyPlan:20,confoundingFlash:21,elunesGrace:22,touchGrave:23});
